name: "Build and Publish Dependency"

on:
  push:
    branches: [develop]

jobs:
  build-publish-release:
    name: Build and Publish RELEASE
    runs-on: ubuntu-latest

    if: (github.event_name == 'release' && github.event.action == 'created')
